name: Build & Push to GHCR + Bump ops-repo
on: { push: { branches: ["main"] }, workflow_dispatch: {} }
env:
  IMAGE_NAME: ghcr.io/<OWNER>/oi-was   # ← 소유자 맞게

jobs:
  build-push-and-bump:
    runs-on: ubuntu-latest
    permissions: { contents: write, packages: write }
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        with: { install: true }

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHORT_SHA }}
            ${{ env.IMAGE_NAME }}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ops-repo 수정
      - name: Checkout ops-repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.OPS_REPO }}     # ex) <OWNER>/k8s
          token: ${{ secrets.OPS_REPO_PAT }}      # repo 권한 PAT
          path: ops
          fetch-depth: 0

      - name: Bump image tag
        working-directory: ops
        shell: bash
        run: |
          set -euo pipefail
          FILE="k8s/deployment.yaml"
          NEW="${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHORT_SHA }}"
          sed -i -E 's|^(\s*image:\s*).*|\1'"$NEW"'|' "$FILE"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FILE"; git commit -m "chore(ci): $NEW" || echo "no change"
          git push || true
